FROM wordpress:5.1.0-php7.2-apache

# RUN apt-get update \
#     && apt-get install -y zlib1g-dev \
#     && rm -rf /var/lib/apt/lists/* \
#     && docker-php-ext-install zip 

# RUN chown -R www-data:www-data /var/www
# RUN find /var/www/ -type d -exec chmod 0755 {} \;
# RUN find /var/www/ -type f -exec chmod 644 {} \


# Simply run same commands as in example above
# $ mkdir /var/www/html/wp-content/plugins
# $ mkdir /var/www/html/wp-content/uploads
# $ chown -R www-data:www-data /var/www
# $ find /var/www/ -type d -exec chmod 0755 {} \;
# $ find /var/www/ -type f -exec chmod 644 {} \;